/**
 * Registry of Canonical Existing Datasets in the Lab
 */

export const EXISTING_DATASETS_REGISTRY = [
  {
    id: 'packets',
    name: 'packets.parquet (CSV export)',
    filename: 'packets.csv',
    type: 'Packet-Level',
    badgeClass: 'badge-packet',
    description: 'Raw packet-level capture telemetry (packet sizes, IATs, directions F/B, TCP/QUIC headers).',
    rowsHint: 251,
    colsHint: 13,
    url: '/data/packets.csv',
  },
  {
    id: 'flows',
    name: 'flows.parquet (CSV export)',
    filename: 'flows.csv',
    type: 'Flow-Level',
    badgeClass: 'badge-flow',
    description: 'Bidirectional flow aggregates, durations, directional byte volumes, and protocol labels.',
    rowsHint: 5,
    colsHint: 15,
    url: '/data/flows.csv',
  },
  {
    id: 'fingerprint_features',
    name: 'fingerprint_features.csv',
    filename: 'fingerprint_features.csv',
    type: 'ML Fingerprint',
    badgeClass: 'badge-ml',
    description: 'Privacy-preserving fingerprint features (all identity & leakage columns removed).',
    rowsHint: 5,
    colsHint: 43,
    url: '/data/fingerprint_features.csv',
  },
  {
    id: 'full_features',
    name: 'full_features.csv',
    filename: 'full_features.csv',
    type: 'Full Features',
    badgeClass: 'badge-feature',
    description: 'Complete 46 statistical features (packet size/IAT distributions, bursts, activity timing).',
    rowsHint: 5,
    colsHint: 46,
    url: '/data/full_features.csv',
  },
  {
    id: 'early_packets',
    name: 'early_packets.csv',
    filename: 'early_packets.csv',
    type: 'Early Observation',
    badgeClass: 'badge-early',
    description: 'Traffic statistics computed on early packet windows (5, 10, 20, and 30 packets) across all flows.',
    rowsHint: 20,
    colsHint: 47,
    url: '/data/early_packets.csv',
  },
  {
    id: 'captures_meta',
    name: 'captures.csv',
    filename: 'captures.csv',
    type: 'Metadata',
    badgeClass: 'badge-meta',
    description: 'Capture provenance metadata, PCAP file pointers, network scenarios, and repetitions.',
    rowsHint: 5,
    colsHint: 8,
    url: '/data/captures.csv',
  },
];

// Sample default rows for Manual Entry initial demonstration
export const INITIAL_MANUAL_ROWS = [
  {
    id: 'row-1',
    protocol: 'QUIC',
    length: 1250,
    relativeTime: 0.002,
    direction: '→',
    sourceIp: '192.168.1.50',
    sourcePort: 54321,
    destinationIp: '1.1.1.1',
    destinationPort: 443,
  },
  {
    id: 'row-2',
    protocol: 'QUIC',
    length: 980,
    relativeTime: 0.018,
    direction: '←',
    sourceIp: '1.1.1.1',
    sourcePort: 443,
    destinationIp: '192.168.1.50',
    destinationPort: 54321,
  },
  {
    id: 'row-3',
    protocol: 'TCP',
    length: 118,
    relativeTime: 0.035,
    direction: '→',
    sourceIp: '192.168.1.50',
    sourcePort: 54322,
    destinationIp: '8.8.8.8',
    destinationPort: 443,
  },
  {
    id: 'row-4',
    protocol: 'TCP',
    length: 251,
    relativeTime: 0.072,
    direction: '←',
    sourceIp: '8.8.8.8',
    sourcePort: 443,
    destinationIp: '192.168.1.50',
    destinationPort: 54322,
  },
  {
    id: 'row-5',
    protocol: 'QUIC',
    length: 188,
    relativeTime: 0.089,
    direction: '→',
    sourceIp: '192.168.1.50',
    sourcePort: 54323,
    destinationIp: '9.9.9.9',
    destinationPort: 853,
  },
];
